---
# An instance of the Blank widget with a news page element.
# Documentation: https://wowchemy.com/docs/getting-started/page-builder/
widget: blank

# Activate this widget? true/false
active: true

# This file represents a page section.
headless: true

# Order that this section appears on the page.
weight: 50

title: Peer reviewed
subtitle:

design:
  columns: '3'
---


## 2020
**Santos, G.S.**; Vecchi, M.B. & Alves, M.A.S. Transatlantic movement of Domestic Pigeons Columba livia domestica? *Oecologia Australis*. Link  [Graphical abstract]

## 2019
Zucaratto, R.; **Santos, G.S.**; Pires, A.S. & Bergallo, H.G. Coalescing past and present to predict the future: historical attributes and current situation of a non-native palm on an island in the Atlantic Forest in Brazil. Journal of Coastal Conservation. 24(20). 2020. Link.

**Santos, G.S.** Ribeiro, I.C.; Centoducatte, L.D.; Mendes, S.L. (Birds breeding biology and homogenization process in an urban green area at Atlantic rainforest of Southeastern Brazil). Reprodução da avifauna e o processo de homogeneização em uma área verde planejada no sudeste da Mata Atlântica. Neotropical Biology and Conservation. 14(1): 83-98. 2019. Link.

## 2014
**Santos, G.S.** [Distribution and conservation of Double-toothed Kite (Harpagus bidentatus) (Accipitridae) in Espírito Santo, Brazil]. Distribuição e conservação do gavião-ripina (Harpagus bidentatus) (Accipitridae) no Espírito Santo, Brasil. Atualidades Ornitológicas (Impresso), 182: 11-15. 2014. Link.

## 2012
**Santos, G.S.**; Mendes, S. L. ; Pacheco, J. F. [First record of Stygian Owl for Espírito Santo]. Primeiro registro do Mocho-Diabo, Asio stygius, para o estado do Espirito Santo. Atualidades Ornitológicas (Impresso), 169:20. 2012. Link.