---
date: "2016-04-27T00:00:00Z"
external_link: ""
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/georgecushen
slides: example
summary: An example of using the in-built project page.
tags:
- Conservação
- Mata Atlântica
- Ecologia espacial
title: Ungulados - BETA
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
output: html_document
---
```{r include=FALSE}
library(ggplot2)
library(raster)
library(mapview)
library(rnaturalearth)
library(rnaturalearthdata)
library(terra)
library(tidyverse)
library(leaflet)
library(openxlsx)
library(widgetframe)


world <- ne_countries(scale = "medium", returnclass = "sf")
newproj <- raster::crs(world)

UCs_sp=UCs<-rgdal::readOGR(
	dsn = "C:/Artigos e resumos publicados submetidos ideias/Em desenvolvimento/INMA/Script/UCs Brasil _Carol Loss", 
		layer = "uc_bosque-bioma_mar_2020-2_final_v02")


UCs_sf=UCs<-sf::st_as_sf(UCs)

UCs<-UCs%>%
	as(., "Spatial")%>%
		terra::vect(.)

Ung<-read.xlsx(
"C:/Artigos e resumos publicados submetidos ideias/Em desenvolvimento/INMA/Script/Anta_queixada_cateto_UCs_CCMA.xlsx",
			sheet="Planilha1",startRow = 1,  
				detectDates = TRUE, colNames = TRUE)

MA_sp=MA<-rgdal::readOGR(dsn = "C:/Artigos e resumos publicados submetidos ideias/Em desenvolvimento/INMA/Script/UCs Brasil _Carol Loss", layer = "mata_atlantica_bosque_bioma2019_dissolved")
MA<-sf::st_as_sf(MA)
MA<-MA%>%
	as(., "Spatial")%>%
		terra::vect(.)


HFP2009<-raster("C:/Artigos e resumos publicados submetidos ideias/Em desenvolvimento/INMA/Script/HFP2009_MA_low.tif")
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
myleaf<-leaflet() %>%  
 addTiles()  %>%
setView(lat = -15, lng = -45, zoom = 5) %>%
addPolygons(data = UCs_sp, group = "UCs_MA",
            stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.5)%>%
addRasterImage(HFP2009,colors = "inferno",opacity = 1,group = "HFI2009")%>%
addCircleMarkers(data=Ung, lng = ~Long, lat = ~Lat, 
             popup = ~Espécie,group="Ungulados")%>%
addLayersControl(baseGroups = c("OSM (default)"),
	overlayGroups = c("UCs_MA", "HFI2009","Ungulados"))
```



```{r}
frameWidget(myleaf, width = "100%")
```









