---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
profilepic: mariecurie.jpg
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Marie is a Polish and naturalized-French physicist and chemist who conducts pioneering research on radioactivity."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(scholar)
library(tidyverse)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Biological Science, BSC", "2008-2013", "Federal University of Espirito Santo", "Vitória, Brazil ",
  "Ecology & Evolution, MSc", "2014-2016", "Rio de Janeiro State University", "Rio de Janeiro, Brazil",
  "Applied Statistics, Specialization", "2018-2019", "Federal Rural University of Rio de Janeiro", "Rio de Janeiro, Brazil",
  "Ecology & Evolution, PhD", "2017-2021", "Rio de Janeiro State University", "Rio de Janeiro, Brazil"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Selected experiences

```{r}
library(tibble)
tribble(
  ~ Year, ~ Role, ~ Institution, ~ What,
  "Visiting professor", "Mar/2017-Jul/2018", "Rio de Janeiro State University", "Lecture/Course: Sampling design/Biological Science",
  "Visiting researcher", "Aug/2019-Feb/2020", "University of Oxford", "Visiting researcher at the SalgoTeam group",
  "Applied Statistics, Specialization", "2018-2019", "Federal Rural University of Rio de Janeiro", "Rio de Janeiro, Brazil",
  "Ecology & Evolution, PhD", "2017-2021", "Rio de Janeiro State University", "Rio de Janeiro, Brazil"
) %>% 
  detailed_entries(Year,Role,Institution,What)
```

# Publications

#### Summary

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
H<-predict_h_index("DXeK9HwAAAAJ&hl")

pubs<-get_publications("DXeK9HwAAAAJ&hl")

#Pubs total:
pubs%>%select(title)%>%count()

#5 years publications
pubs%>%filter(year > as.numeric(format(Sys.Date(),format="%Y"))-5)%>%select(title)%>%count()

#H-index
```

| Publications                     | Total publications                                                                                | H-Index     | H-Index predict 5-years ahead |
|----------------------------------|---------------------------------------------------------------------------------------------------|-------------|-------------------------------|
| `pubs%>%select(title)%>%count()` | `r  pubs%>%filter(year > as.numeric(format(Sys.Date(),format="%Y"))-5)%>%select(title)%>%count()` | `r  H[1,2]` | `r round(H[6,2],0)`           |
